version: 2
updates:
  # Package partagé
  - package-ecosystem: "npm"
    directory: "/packages/shared"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "Hassan-JERRAR"
    commit-message:
      prefix: "shared"
      include: "scope"

  # Auth service
  - package-ecosystem: "npm"
    directory: "/packages/auth_service"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3
    reviewers:
      - "Hassan-JERRAR"
    commit-message:
      prefix: "auth"
      include: "scope"

  # API Gateway
  - package-ecosystem: "npm"
    directory: "/packages/api_gateway"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3
    reviewers:
      - "Hassan-JERRAR"
    commit-message:
      prefix: "gateway"
      include: "scope"

  # Services métier
  - package-ecosystem: "npm"
    directory: "/packages/company_service"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 2
    reviewers:
      - "Hassan-JERRAR"
    commit-message:
      prefix: "company"

  - package-ecosystem: "npm"
    directory: "/packages/customer_service"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 2
    reviewers:
      - "Hassan-JERRAR"
    commit-message:
      prefix: "customer"

  - package-ecosystem: "npm"
    directory: "/packages/invoice_service"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 2
    reviewers:
      - "Hassan-JERRAR"
    commit-message:
      prefix: "invoice"

  - package-ecosystem: "npm"
    directory: "/packages/quote_service"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 2
    reviewers:
      - "Hassan-JERRAR"
    commit-message:
      prefix: "quote"

  - package-ecosystem: "npm"
    directory: "/packages/product_service"
    schedule:
      interval: "weekly"
      day: "wednesday"
    open-pull-requests-limit: 2
    reviewers:
      - "Hassan-JERRAR"
    commit-message:
      prefix: "product"

  - package-ecosystem: "npm"
    directory: "/packages/stripe_service"
    schedule:
      interval: "weekly"
      day: "wednesday"
    open-pull-requests-limit: 2
    reviewers:
      - "Hassan-JERRAR"
    commit-message:
      prefix: "stripe"

  - package-ecosystem: "npm"
    directory: "/packages/dashboard_service"
    schedule:
      interval: "weekly"
      day: "wednesday"
    open-pull-requests-limit: 2
    reviewers:
      - "Hassan-JERRAR"
    commit-message:
      prefix: "dashboard"

  - package-ecosystem: "npm"
    directory: "/packages/email_service"
    schedule:
      interval: "weekly"
      day: "thursday"
    open-pull-requests-limit: 2
    reviewers:
      - "Hassan-JERRAR"
    commit-message:
      prefix: "email"

  - package-ecosystem: "npm"
    directory: "/packages/pdf_service"
    schedule:
      interval: "weekly"
      day: "thursday"
    open-pull-requests-limit: 2
    reviewers:
      - "Hassan-JERRAR"
    commit-message:
      prefix: "pdf"

  - package-ecosystem: "npm"
    directory: "/packages/ai_service"
    schedule:
      interval: "weekly"
      day: "thursday"
    open-pull-requests-limit: 2
    reviewers:
      - "Hassan-JERRAR"
    commit-message:
      prefix: "ai"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    reviewers:
      - "Hassan-JERRAR"
    commit-message:
      prefix: "ci"