name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  # Job pour détecter les changements dans les services
  changes:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.changes.outputs.changes }}
      api_gateway: ${{ steps.changes.outputs.api_gateway }}
      auth_service: ${{ steps.changes.outputs.auth_service }}
      ai_service: ${{ steps.changes.outputs.ai_service }}
      company_service: ${{ steps.changes.outputs.company_service }}
      customer_service: ${{ steps.changes.outputs.customer_service }}
      dashboard_service: ${{ steps.changes.outputs.dashboard_service }}
      email_service: ${{ steps.changes.outputs.email_service }}
      invoice_service: ${{ steps.changes.outputs.invoice_service }}
      pdf_service: ${{ steps.changes.outputs.pdf_service }}
      product_service: ${{ steps.changes.outputs.product_service }}
      quote_service: ${{ steps.changes.outputs.quote_service }}
      stripe_service: ${{ steps.changes.outputs.stripe_service }}
      shared: ${{ steps.changes.outputs.shared }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            api_gateway:
              - 'packages/api_gateway/**'
            auth_service:
              - 'packages/auth_service/**'
            ai_service:
              - 'packages/ai_service/**'
            company_service:
              - 'packages/company_service/**'
            customer_service:
              - 'packages/customer_service/**'
            dashboard_service:
              - 'packages/dashboard_service/**'
            email_service:
              - 'packages/email_service/**'
            invoice_service:
              - 'packages/invoice_service/**'
            pdf_service:
              - 'packages/pdf_service/**'
            product_service:
              - 'packages/product_service/**'
            quote_service:
              - 'packages/quote_service/**'
            stripe_service:
              - 'packages/stripe_service/**'
            shared:
              - 'packages/shared/**'

  # Job pour les tests et build
  test-and-build:
    needs: changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api_gateway, auth_service, ai_service, company_service, customer_service, dashboard_service, email_service, invoice_service, pdf_service, product_service, quote_service, stripe_service]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm ci
          npx lerna bootstrap || npm install
          
      - name: Fix security vulnerabilities
        run: npm audit fix --force
        continue-on-error: true
      
      - name: Build shared package if changed
        if: needs.changes.outputs.shared == 'true'
        run: |
          cd packages/shared
          npm run build || npm run tsc || echo "No build script for shared package"
      
      - name: Test and build service
        if: contains(needs.changes.outputs.*, matrix.service) == 'true' || needs.changes.outputs.shared == 'true'
        run: |
          cd packages/${{ matrix.service }}
          
          # Install dependencies si pas déjà fait
          npm install || true
          
          # Run tests si disponibles
          if npm run | grep -q "test"; then
            npm test
          else
            echo "No tests available for ${{ matrix.service }}"
          fi
          
          # Build si disponible
          if npm run | grep -q "build"; then
            npm run build
          else
            echo "No build script for ${{ matrix.service }}"
          fi

  # Job pour construire et publier les images Docker
  build-and-push:
    needs: [changes, test-and-build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    strategy:
      matrix:
        service: [api_gateway, auth_service, ai_service, company_service, customer_service, dashboard_service, email_service, invoice_service, pdf_service, product_service, quote_service, stripe_service]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm ci
          npx lerna bootstrap || npm install
      
      - name: Build shared package
        run: |
          cd packages/shared
          npm run build || npm run tsc || echo "No build script for shared package"
      
      - name: Build service
        if: contains(needs.changes.outputs.*, matrix.service) == 'true' || needs.changes.outputs.shared == 'true'
        run: |
          cd packages/${{ matrix.service }}
          npm install || true
          if npm run | grep -q "build"; then
            npm run build
          fi
      
      - name: Log in to Container Registry
        if: contains(needs.changes.outputs.*, matrix.service) == 'true' || needs.changes.outputs.shared == 'true'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_TOKEN }}
      
      - name: Extract metadata
        if: contains(needs.changes.outputs.*, matrix.service) == 'true' || needs.changes.outputs.shared == 'true'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/zenbilling-${{ matrix.service }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
      
      - name: Build and push Docker image
        if: contains(needs.changes.outputs.*, matrix.service) == 'true' || needs.changes.outputs.shared == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: packages/${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  # Job pour déclencher le déploiement sur Coolify
  deploy:
    needs: [changes, build-and-push]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    strategy:
      matrix:
        service: [api_gateway, auth_service, ai_service, company_service, customer_service, dashboard_service, email_service, invoice_service, pdf_service, product_service, quote_service, stripe_service]
    
    steps:
      - name: Deploy to Coolify
        if: contains(needs.changes.outputs.*, matrix.service) == 'true' || needs.changes.outputs.shared == 'true'
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.COOLIFY_WEBHOOK_URL_PREFIX }}-${{ matrix.service }}
          method: 'GET'
          timeout: 60000