name: Cleanup Registry

on:
  schedule:
    # Chaque dimanche à 02:00 UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Mode dry-run (ne supprime pas réellement)'
        required: true
        type: boolean
        default: true
      keep_count:
        description: 'Nombre d''images à conserver par service'
        required: true
        type: number
        default: 10

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: zenbilling

jobs:
  cleanup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - api-gateway
          - auth-service
          - company-service
          - customer-service
          - dashboard-service
          - email-service
          - invoice-service
          - pdf-service
          - product-service
          - quote-service
          - stripe-service
          - ai-service
    steps:
      - name: Cleanup old images
        uses: actions/delete-package-versions@v4
        with:
          package-name: ${{ env.IMAGE_PREFIX }}-${{ matrix.service }}
          package-type: container
          min-versions-to-keep: ${{ github.event.inputs.keep_count || 10 }}
          delete-only-untagged-versions: false
          token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: ${{ github.event.inputs.dry_run || false }}

  cleanup-summary:
    runs-on: ubuntu-latest
    needs: cleanup
    if: always()
    steps:
      - name: Cleanup Summary
        run: |
          echo "🧹 Nettoyage du registry terminé"
          echo "Mode: ${{ github.event.inputs.dry_run == 'true' && 'DRY RUN' || 'REAL CLEANUP' }}"
          echo "Images conservées par service: ${{ github.event.inputs.keep_count || 10 }}"
          
          if [[ "${{ needs.cleanup.result }}" == "success" ]]; then
            echo "✅ Nettoyage réussi pour tous les services"
          else
            echo "⚠️ Certains services ont eu des problèmes lors du nettoyage"
          fi