name: Minimal Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api_gateway, auth_service, ai_service, company_service, customer_service, dashboard_service, email_service, invoice_service, pdf_service, product_service, quote_service, stripe_service]
      max-parallel: 2
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm ci --audit=false --silent
        continue-on-error: true
      
      - name: Build service
        run: |
          cd packages/${{ matrix.service }}
          npm install --audit=false --silent || echo "Install completed"
          if [ -f "package.json" ] && npm run | grep -q "build"; then
            npm run build || echo "Build completed with warnings"
          fi
        continue-on-error: true
      
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: packages/${{ matrix.service }}/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/zenbillingapp/zenbilling-${{ matrix.service }}:latest
            ${{ env.REGISTRY }}/zenbillingapp/zenbilling-${{ matrix.service }}:${{ github.sha }}
      
      - name: Deploy to Coolify
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.COOLIFY_WEBHOOK_URL_PREFIX }}${{ matrix.service }}
          method: 'GET'
          timeout: 120000
        continue-on-error: true
      
      - name: Wait between deployments
        run: sleep 10